[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 3

# Social Media Configuration

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/bestend"
    weight = 1

[[social]]
    identifier = "email"
    name = "Email"
    url = "mailto:infend@gmail.com"
    weight = 2
